# install opentelemetry-operator first
# $ kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/latest/download/opentelemetry-operator.yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: app
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.85"
    - name: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
      value: "true"
  exporter:
    endpoint: http://otel-collector-collector:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    env:
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: OTEL_TRACES_EXPORTER
        value: otlp_proto_http
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector:4318
      - name: OTEL_METRICS_EXPORTER
        value: none